### ISSUE TITLE
5.4.2 CREATING THE ENVOY CONTAINER IMAGE - wrong filename

### ISSUE THREAD

**Issue by vrms** [luksa/kubernetes-in-action-2nd-edition#13]
In the mentioned chapter you say about the `kiada-ssl-proxy-image`directory:

_"It also contains the `envoy.conf` config file"_

However in reality that file in this repo here seems to be named [`envoy.yaml`](https://github.com/luksa/kubernetes-in-action-2nd-edition/blob/master/Chapter05/kiada-ssl-proxy-0.1/envoy.yaml), not `envoy.conf`.

**Comment by luksa** [comment]
Yes, the correct file name is envoy.yaml. Thanks for reporting.
