### ISSUE TITLE
DEPLOYING A POD WITH INIT CONTAINERS - failes (probably due to wrong ping)

### ISSUE THREAD

**Issue by vrms** [luksa/kubernetes-in-action-2nd-edition#14]
Chapter05 Section 5.5.2

execution fails as shown below:

```
kubectl get events -w
...
...
0s          Normal    Created     pod/kiada-init   Created container network-check
0s          Normal    Started     pod/kiada-init   Started container network-check
0s          Warning   BackOff     pod/kiada-init   Back-off restarting failed container
```

The Book says:

> "The second init container performs a network connectivity test by using the ping command to check if a specific IP address is reachable from within the pod. The IP address is configurable via a command-line argument which defaults to 1.1.1.1"_

however it is nowhere expaine how to apply the mentioned _command-line argumet_, so there is not clue how to actually ping an IP address which can be reached (and likewise get this working)

So, what is missing in the book is an **example how to pass reachable ip addresse as a argument to the execution of `kcl apply -f pod.kiada-init.yaml`**

**Comment by vrms** [comment]
I tried to get aroung this by

1. editng the `docker_entrypoint.sh`, replacing `1.1.1.1` with one of the ips of currently running pod 
1. build my own `network-connectivity-check` image and
1. reference to that in the `kiada-init.yaml`

however I am unable to make this custom image pullable from my node (due to personal lack of knowledge)

**Comment by luksa** [comment]
I've added an example YAML that shows how to set the IP address to ping.  See https://github.com/luksa/kubernetes-in-action-2nd-edition/commit/048adbbe2c85ebec7d649d7feb25f8dcdcde0406#diff-17d548367c1121030e1bf331e291035713183aeb5276ee7ca6804dbad3633aeb

Hope this helps.

**Comment by vrms** [comment]
thanks for the immediate action. However I am failing in the same manner as before even with the new `pod.kiada-init.custom-ip.yaml`

```
kubectl get events -w
...
0s          Normal    Pulled      pod/kiada-init   Container image "luksa/network-connectivity-checker:0.1" already present on machine
0s          Normal    Created     pod/kiada-init   Created container network-check
0s          Normal    Started     pod/kiada-init   Started container network-check
0s          Warning   BackOff     pod/kiada-init   Back-off restarting failed container
...
...
```

**Comment by luksa** [comment]
Try `kubectl describe` to see what the container exit code is to see why it keeps getting restarted. You can also check the container's log with `kubectl logs kiada-init -c network-check`.

**Comment by luksa** [comment]
You're probably behind a corporate firewall. I should probably add notes about this throughout the book, but I don't have time to go through all the exercises to figure out where the firewall would cause problems.
